-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Telekinesis",
    [2] = "Telekinesis",
    [3] = "Telekinesis"
}

game:GetService("ReplicatedStorage").EventRemotes.ForgeUltimateSword:FireServer(unpack(args))
